services:
  - type: web
    name: backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: REDIS_URL
        value: ""
      - key: DATABASE_URL
        value: ""
      # Add other secrets or keys as needed

